ArrayList<Integer> estArrivalTimeArray = new ArrayList<Integer>(); 
ArrayList<Integer> arrivalTimeArray = new ArrayList<Integer>();
ArrayList<Integer> seperateByTime = new ArrayList<Integer>();
WidgetContainer theWidgetContainer = new WidgetContainer();
ArrayList<Widget> linePlotArray = new ArrayList<Widget>();
ArrayList<String> carrierArray = new ArrayList<String>();
ArrayList<Float> cancelledArray = new ArrayList<Float>();
ArrayList<Float> divertedArray = new ArrayList<Float>();
ArrayList<Integer> dateCount = new ArrayList<Integer>();
ArrayList<String> airports = new ArrayList<String>();
ArrayList<String> city = new ArrayList<String>();
ArrayList<DataPoint> dataPoints;
usaMap theMap = new usaMap();
PrintPieChart cancellations;
defaultBackEnd foundation;
PrintPieChart diversions;
Histogram airportCounter;
DataPrinter10 printer10;
DataPrinter11 printer11;
DataPrinter12 printer12;
DataPrinter13 printer13;
DataPrinter14 printer14;
DataPrinter15 printer15;
DataPrinter16 printer16;
DataPrinter17 printer17;
DataPrinter18 printer18;
DataPrinter19 printer19;
DataPrinter20 printer20;
DataPrinter21 printer21;
DataPrinter22 printer22;
DataPrinter23 printer23;
DataPrinter24 printer24;
DataPrinter25 printer25;
DataPrinter26 printer26;
DataPrinter27 printer27;
DataPrinter28 printer28;
DataPrinter29 printer29;
DataPrinter30 printer30;
DataPrinter31 printer31;
DataPrinter1 printer1;
DataPrinter2 printer2;
DataPrinter3 printer3;
DataPrinter4 printer4;
DataPrinter5 printer5;
DataPrinter6 printer6;
DataPrinter7 printer7;
DataPrinter8 printer8;
DataPrinter9 printer9;
//PieChart thePieChart;
Histogram carrier;
HomePage thePage;
int screen = 0;
Gif loopingGif;
int entry = 0;
PImage clouds;
Dates dates;
Table table;
Exit exit1;
Exit exit2;
Exit exit3;
Exit exit4;
Exit exit5;
Exit exit6;
Exit exit7;
int[] c;
int[] d;
int a;
int b;

final int EVENT_BUTTON1=1;
final int EVENT_BUTTON2=2;
final int EVENT_BUTTON3=3;
final int EVENT_BUTTON4=4;
final int EVENT_BUTTON5=5;
final int EVENT_BUTTON6=6;
final int EVENT_BUTTON7=7;
final int EVENT_BUTTON8=8;
final int EVENT_NULL=0;
final int GAP=10;
final int radius = 15;
final int SCREENX = 1920;
final int MARGIN = 160;
final int SCREENY = 960;
final int EVENT_EXIT=-1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Collections;
import java.util.Set;
import java.util.HashSet;
import processing.pdf.*;
import gifAnimation.*;
import java.util.Map;
